### ISSUE TITLE
run

### ISSUE THREAD

**Issue by Steafan-Xiong** [zZhiG/DECS-Net#1]
Tere is no train.py.I want to know how to run the DECS-Net ,thanks

**Comment by zZhiG** [comment]
A simple training code has been uploaded.
https://github.com/zZhiG/DECS-Net/blob/main/train.py

**Comment by zZhiG** [comment]
> Tere is no train.py.I want to know how to run the DECS-Net ,thanks

A simple training code has been uploaded.
https://github.com/zZhiG/DECS-Net/blob/main/train.py

**Comment by zty-acc** [comment]
Could you please provide the complete test code? I would like to run it and evaluate the full set of experimental metrics. Thank you.
